language: python
python:
 - "3.3"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - pip install nose==1.3.0
 - pip install coverage==3.6

before_script:
 - python setup.py install

script:
 - nosetests -v --with-coverage --cover-package=spcControl
